"""add had_fallback to messages

Revision ID: 10ec5cddd182
Revises: c3d7f2a91b05
Create Date: 2026-04-11 19:46:42.909920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10ec5cddd182"
down_revision: Union[str, Sequence[str], None] = "c3d7f2a91b05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("had_fallback", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "had_fallback")
    # ### end Alembic commands ###
