"""add_plan_and_stripe_customer_id_to_users

Revision ID: 23d1984e11ea
Revises: 10ec5cddd182
Create Date: 2026-04-21 07:22:24.776070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d1984e11ea'
down_revision: Union[str, Sequence[str], None] = '10ec5cddd182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
