"""add raw_text to documents

Revision ID: 841ece4a0533
Revises: 16bbf5dbe349
Create Date: 2026-03-14 12:07:32.069452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841ece4a0533'
down_revision: Union[str, Sequence[str], None] = '16bbf5dbe349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_text')
    # ### end Alembic commands ###
